[[constraint]]
  name = "github.com/Sirupsen/logrus"
  branch = "master"

[[constraint]]
  name = "github.com/beevik/etree"
  version = "1.1.0"

[[constraint]]
  name = "github.com/bitrise-io/bitrise"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/envman"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/goinp"

[[constraint]]
  name = "github.com/bitrise-io/stepman"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-io/go-xcode"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-io/xcode-project"
  branch = "master"

[[constraint]]
  name = "github.com/google/go-cmp"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"

[[constraint]]
  name = "github.com/urfave/cli"
  branch = "master"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  branch = "v2"

[prune]
  go-tests = true
  unused-packages = true