
[[constraint]]
  name = "github.com/beevik/etree"
  version = "1.1.0"

# Enforcing this to use bitrise.yml version (8) currently supported by website 
[[constraint]]
  name = "github.com/bitrise-io/bitrise"
  version = "=1.31.0"

[[constraint]]
  name = "github.com/bitrise-io/envman"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-xcode"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/goinp"

[[constraint]]
  name = "github.com/bitrise-io/stepman"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/xcode-project"

[[constraint]]
  name = "github.com/google/go-cmp"
  version = "0.3.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/urfave/cli"
  revision = "e6cf83ec39f6e1158ced1927d4ed14578fda8edb"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[prune]
  go-tests = true
  unused-packages = true
